language: csharp
mono:
  - latest

solution: PokeD.ServerProxy.Desktop.sln

before_install:
  - git submodule update --init --recursive
  
install:
  - nuget restore PokeD.ServerProxy.Desktop.sln

script:
  - xbuild /p:Configuration=Release PokeD.ServerProxy.Desktop.sln
  - xbuild /p:Configuration=Debug PokeD.ServerProxy.Desktop.sln

notifications:
  email:
    on_success: always
